### ISSUE TITLE
[CMake] Name conflict causes a compile error

### ISSUE THREAD

**Issue by SunBlack** [quickjs-ng/quickjs#1241]
When updating CMake 3.30.1 to 3.31.9 in the vcpkg repository (https://github.com/microsoft/vcpkg/pull/48250), a compilation error occurred with this library here. The reason for the compile error is that vcpkg uses Ninja for compiling, which is highly parallelized. This can cause issues if two targets have the same name, as additional files, such as PDBs, are often created.

Here a library named `qjs` will be created
https://github.com/quickjs-ng/quickjs/blob/6a9fe9af5ca0bf7c49ae697edef44864272317d1/CMakeLists.txt#L256

And here the executable will be renamed to the same name

https://github.com/quickjs-ng/quickjs/blob/6a9fe9af5ca0bf7c49ae697edef44864272317d1/CMakeLists.txt#L305-L307

As `qjs_exe` doesn't link against `qjs`, assumes that it can be compiled in parallel - because of the same name, the compiler wants to create a PDB with the same name at the same time, which leads to the following issue:
```
LINK : fatal error LNK1201: error writing to program database 'D:\b\quickjs-ng\x64-windows-static-dbg\qjs.pdb'; check for insufficient disk space, invalid path, or insufficient privilege
```

The best solution would be to avoid renaming targets so that conflicts do not arise. In the vcpkg repository, we will rename the PDB file as a temporary patch, but this does not prevent possible issues arising from identical file names in other compilers.

**Comment by saghul** [comment]
> As `qjs_exe` doesn't link against `qjs`

But it does: https://github.com/quickjs-ng/quickjs/blob/6a9fe9af5ca0bf7c49ae697edef44864272317d1/CMakeLists.txt#L309

**Comment by saghul** [comment]
I'd say the patch in https://github.com/microsoft/vcpkg/pull/48250/files#diff-b009aac678fb1c7aaeb6e43d479f680a66ea2b961f0e13b4d3df41e36b937eed is acceptable.

**Comment by mvanhorn** [comment]
Implemented in https://github.com/quickjs-ng/quickjs/pull/1474 - unique PDB_NAME per target so qjs and qjs_exe don't collide on Windows parallel builds.
