### ISSUE TITLE
build with gcc 15.1 failed with error: 'unterminated-string-initialization'

### ISSUE THREAD

**Issue by terrywh** [quickjs-ng/quickjs#1053]
* quickjs: v0.10.0
* gcc: v15.1.0
* uname: `Linux VM-193-107-tencentos 6.6.80-29.tl4.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 24 21:16:21 CST 2025 x86_64 x86_64 x86_64 GNU/Linux`
* error:
``` bash
/data/stage/quickjs-0.10.0/quickjs.c:11727:32: error: initializer-string for array of ‘char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (37 chars into 36 available) [-Werror=unterminated-string-initialization]
11727 | static char const digits[36] = "0123456789abcdefghijklmnopqrstuvwxyz";
```
